apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: kahoot-bot-deploy-
spec:
  entrypoint: deploy-kahoot-bot
  templates:
  - name: deploy-kahoot-bot
    steps:
    - - name: clone-repo
        template: clone-repo
    - - name: build-and-push
        template: build-and-push-image

  - name: clone-repo
    container:
      image: alpine/git:latest
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "Cloning the GitHub repository"
          git clone https://github.com/Feelfeel20088/Just_Another_Kahootbot.git /src

  - name: build-and-push-image
    container:
      image: docker:19.03.12
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "Building Docker image for Just_Another_Kahoot_Bot"
          cd /src
          docker build -t feelfeel200088/just_another_kahoot_bot:latest .
          echo "Pushing Docker image to Docker Hub"
          docker push feelfeel200088/just_another_kahoot_bot:latest
