
apiVersion: apps/v1
kind: Deployment
metadata:
  name: just-another-kahoot-bot
  namespace: utility # or your namespace
spec:
  replicas: 3 # this should auto scale on its own but 3 is a good starting amount
  selector:
    matchLabels:
      app: just-another-kahoot-bot
  template:
    metadata:
      labels:
        app: just-another-kahoot-bot
    spec:
      containers:
        - name: just-another-kahoot-bot
          image: feelfeel200088/just_another_kahoot_bot
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "8Gi"  # Limit memory to Gi 
              cpu: "1"        # Limit CPU to 1 thread
---
apiVersion: v1
kind: Service
metadata:
  name: just-another-kahoot-bot-external
  namespace: utility
spec:
  selector:
    app: just-another-kahoot-bot
  ports:
    - protocol: TCP
      port: 8000       # External port
      targetPort: 8000  # Container port
      nodePort: 30005    # Expose on NodePort 30005 or replace with your own nodeport
  type: NodePort  # Exposes the service externally
---
apiVersion: v1
kind: Service
metadata:
  name: just-another-kahoot-bot-internal
  namespace: utility
spec:
  selector:
    app: just-another-kahoot-bot
  ports:
    - protocol: TCP
      port: 8000       # Internal port
      targetPort: 8000  # Target port on the pod
  type: ClusterIP  # Internal-only service
