{{- if .Values.internalService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kahoot-bot.fullname" . }}-internal
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "kahoot-bot.fullname" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
  type: ClusterIP
{{- end }}
